// Shared constants — every magic number in feature code must trace back to here.

export const SLOT_HOLD_MINUTES = 10
export const HOLD_WARNING_SECONDS = 120 // timer turns amber
export const SLOT_WINDOW_DAYS = 30 // generation lookahead (matches Edge Function)
// Bookings per branch per DAY (NOT per slot). The DB generates exactly this
// many capacity-1 slots/day — see migration 20260726151039. Column authoritative.
export const DEFAULT_SLOT_ALLOCATION = 5
export const BOOKING_REF_PREFIX = 'IH' // refs generated by DB trigger, never in TS
export const SMS_MAX_LENGTH = 140
export const CURRENCY = 'EGP'
export const EGYPT_DIAL_CODE = '+20'
export const OTP_LENGTH = 6
export const OTP_RESEND_SECONDS = 60
