// Shared constants — every magic number in feature code must trace back to here.

export const SLOT_HOLD_MINUTES = 10
export const HOLD_WARNING_SECONDS = 120 // timer turns amber
export const SLOT_WINDOW_DAYS = 30 // generation lookahead (matches Edge Function)
// Bookings per branch per DAY (NOT per slot). The DB generates exactly this
// many capacity-1 slots/day — see migration 20260726151039. Column authoritative.
export const DEFAULT_SLOT_ALLOCATION = 5
export const BOOKING_REF_PREFIX = 'IH' // refs generated by DB trigger, never in TS
export const SMS_MAX_LENGTH = 140
export const CURRENCY = 'EGP'
export const EGYPT_DIAL_CODE = '+20'
export const OTP_LENGTH = 6
export const OTP_RESEND_SECONDS = 60

/**
 * Supabase Auth static test numbers (fixed OTP `123456`, real sessions issued,
 * no SMS sent by the auth provider). Used by every E2E flow and by the Node
 * verification scripts.
 *
 * ⚠ NOTHING may send a real SMS to these numbers — they are not real phones.
 * `settle-payment` skips the confirmation SMS for them; keep that guard in step
 * with this list (the Edge Function mirrors it).
 */
export const STATIC_TEST_PHONES = ['+201000000001', '+201000000002'] as const

/**
 * Patient-facing support channels (PROF-01 «تواصل معنا»).
 * ⚠ ALL NULL — the founder has not supplied the real patient-support contact
 * yet (flagged in PROGRESS). NULL means the profile row HIDES: empty means
 * absent, never a fake number the desk cannot answer.
 */
export const PATIENT_SUPPORT: {
  readonly whatsapp: string | null
  readonly phone: string | null
  readonly email: string | null
} = {
  whatsapp: null,
  phone: null,
  email: null,
}
