import { ADMIN_ACCENT } from '@instahealth/design-tokens'
import QRCode from 'qrcode'

import type { EnrollStart } from '../../app/admin/actions'
import { Alert } from '../ui/Alert'
import { Logo } from '../ui/Logo'
import { AdminEnrollForm } from './AdminEnrollForm'

// Screen D — the enrollment card. A centred panel, NOT the two-panel doorway:
// enrolling is a task you complete, not a threshold you cross.
export async function AdminEnrollCard({
  enrollment,
}: {
  enrollment: { ok: true; data: EnrollStart } | { ok: false; errorAr: string }
}) {
  if (!enrollment.ok) {
    return (
      <div
        dir="rtl"
        className="flex min-h-screen items-center justify-center bg-ih-neutral-100 p-8"
      >
        <div className="w-full max-w-[520px]">
          <Alert type="error" testId="admin-enroll-error">
            {enrollment.errorAr}
          </Alert>
        </div>
      </div>
    )
  }

  const { factorId, uri, secret } = enrollment.data

  // The QR is rendered to an inline SVG on the SERVER. No canvas, no client
  // library, no network request — and critically the secret never becomes an
  // <img src> that could land in a proxy log or a browser cache.
  const qrSvg = await QRCode.toString(uri, {
    type: 'svg',
    margin: 0,
    errorCorrectionLevel: 'M',
    color: { dark: '#023449', light: '#FFFFFF' },
  })

  return (
    <div
      dir="rtl"
      className="flex min-h-screen items-center justify-center bg-ih-neutral-100 p-8 font-arabic"
    >
      <div className="w-full max-w-[760px] overflow-hidden rounded-2xl border border-ih-neutral-200 bg-white shadow-sm">
        <div
          className="flex items-center gap-3 px-[22px] py-[18px]"
          style={{ background: ADMIN_ACCENT.ink }}
        >
          <Logo variant="white" size={30} />
          <div className="flex flex-col gap-0.5">
            <span className="text-[15px] font-extrabold text-white">
              فعّل الخطوة الثانية قبل الدخول
            </span>
            <span className="text-[12px] text-white/80">إجراء لمرة واحدة — لا يمكن تخطّيه</span>
          </div>
        </div>

        {/* ⚠ `220px minmax(0,1fr)` per the handoff. The 1fr is written as
            minmax(0,1fr) deliberately — VIEW-01 showed a bare `1fr` cannot
            shrink below its content's min-content width and overflows a
            hidden container instead. */}
        <div className="grid grid-cols-[220px_minmax(0,1fr)] items-start gap-[22px] p-[22px] max-lg:grid-cols-1">
          <div className="flex flex-col items-center gap-2.5">
            <div
              className="flex h-[180px] w-[180px] items-center justify-center rounded-xl border-[1.5px] border-ih-neutral-200 bg-white p-3"
              data-testid="admin-enroll-qr"
              // The SVG is generated by `qrcode` from a URI we constructed
              // server-side — not user input, and never rendered as HTML from
              // anything a request could influence.
              dangerouslySetInnerHTML={{ __html: qrSvg }}
            />
            <span className="text-center text-[11.5px] leading-[1.6] text-ih-neutral-600">
              امسحه بتطبيق المصادقة
              <br />
              (Google Authenticator أو Authy)
            </span>
            <span
              dir="ltr"
              data-testid="admin-enroll-secret"
              className="rounded-md bg-ih-neutral-100 px-2.5 py-1.5 text-[11.5px] font-bold tracking-[0.08em] text-ih-neutral-700"
              style={{ fontFamily: 'var(--font-atkinson), sans-serif' }}
            >
              {/* Grouped in fours, exactly as the design shows the manual key —
                  it is going to be typed by hand on a phone. */}
              {secret.replace(/(.{4})/g, '$1 ').trim()}
            </span>
            <span className="text-center text-[11px] text-ih-neutral-500">
              أو أدخل هذا المفتاح يدوياً
            </span>
          </div>

          <AdminEnrollForm factorId={factorId} />
        </div>
      </div>
    </div>
  )
}
