CREATE INDEX idx_branches_geo ON branches (lat, lng) WHERE is_active = TRUE AND holiday_mode = FALSE;
CREATE INDEX idx_branches_governorate ON branches (governorate, is_active);
CREATE INDEX idx_branches_provider ON branches (provider_id);
CREATE INDEX idx_slots_branch_date ON slots (branch_id, slot_date);
CREATE INDEX idx_slots_available ON slots (branch_id, slot_date, slot_time) WHERE is_blocked = FALSE AND booked_count < capacity;
CREATE INDEX idx_slot_holds_expires ON slot_holds (expires_at);
CREATE INDEX idx_slot_holds_slot ON slot_holds (slot_id, expires_at);
CREATE INDEX idx_slot_holds_user ON slot_holds (user_id);
CREATE INDEX idx_bookings_user ON bookings (user_id, created_at DESC);
CREATE INDEX idx_bookings_branch_date ON bookings (branch_id, created_at DESC);
CREATE INDEX idx_bookings_branch_active ON bookings (branch_id, status) WHERE status IN ('confirmed', 'pending');
CREATE INDEX idx_bookings_ref ON bookings (booking_ref);
CREATE INDEX idx_bookings_paymob ON bookings (paymob_order_id) WHERE paymob_order_id IS NOT NULL;
CREATE INDEX idx_bookings_status_date ON bookings (status, created_at DESC);
CREATE INDEX idx_branch_services_service ON branch_services (service_id, is_available) WHERE is_available = TRUE;
CREATE INDEX idx_branch_services_branch ON branch_services (branch_id);
CREATE INDEX idx_reviews_branch ON reviews (branch_id, rating) WHERE is_flagged = FALSE;
CREATE INDEX idx_provider_users_auth ON provider_users (auth_user_id) WHERE is_active = TRUE;
CREATE INDEX idx_notifications_pending ON notifications (status, created_at) WHERE status = 'pending';
CREATE INDEX idx_payments_booking ON payments (booking_id);
CREATE INDEX idx_payments_status_date ON payments (status, created_at DESC);
